[package]
name = "clewdr"
version = "0.1.2"
edition = "2024"
authors = ["Xerxes-2"]

[lib]
path = "src/lib/lib.rs"

[dependencies]
tokio = { version = "0.1.2"] }
rquest = { version = "0.1.2"] }
rquest-util = "2"
serde_json = "1"
const_format = { version = "0.1.2"] }
figlet-rs = "0.1"
serde = { version = "0.1.2"] }
toml = "0.8"
colored = "3"
axum = { version = "0.1.2", features = [
    "json",
    "tracing",
    "tokio",
    "macros",
    "http2",
] }
regex = "1"
tracing = { version = "0.1.2", features = [
    "max_level_debug",
    "release_max_level_info",
] }
tracing-subscriber = { version = "0.1.2"] }
rand = "0.9"
chrono = "0.4"
parking_lot = { version = "0.1.2"] }
futures = "0.3"
thiserror = "2"
uuid = { version = "0.1.2"] }
tower-http = { version = "0.1.2"] }
clap = { version = "0.1.2"] }
async-trait = "0.1"
futures-util = "0.3"
base64 = "0.22"
itertools = "0.14"
